(ns app.i18n.es-MX (:require untangled.i18n.core) (:import goog.module.ModuleManager))

;; This file was generated by untangled's i18n leiningen plugin.

(def
 translations
 {"|<===>" "",
  "|<Back" "",
  "|Forward>" "",
  "|Frame {f,number} of {end,number} " "",
  "|{ts,date,short} {ts,time,long}" "",
  "|By {author}" "Por {author}",
  "|Show comments" "Mostrar comentarios"})

(swap!
 untangled.i18n.core/*loaded-translations*
 (fn [x] (assoc x "es-MX" translations)))

(if
 (exists? js/i18nDevMode)
 :noop
 (-> goog.module.ModuleManager .getInstance (.setLoaded "es-MX")))